# Generated by Django 4.1.7 on 2023-02-23 14:21

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
