# Generated by Django 4.1.7 on 2023-02-23 14:37

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_state_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
